"""create assistants table

Revision ID: 05515c303079
Revises: 
Create Date: 2026-08-25 02:21:19.229525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05515c303079'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('langflow_flow_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assistants_project_flow', 'assistants', ['project_id', 'langflow_flow_id'], unique=True)
    op.create_index(op.f('ix_assistants_project_id'), 'assistants', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistants_project_id'), table_name='assistants')
    op.drop_index('ix_assistants_project_flow', table_name='assistants')
    op.drop_table('assistants')
    # ### end Alembic commands ###
